import foundations from './foundations.js';
import runtime from './runtime.js';
import context from './context.js';
import orchestration from './orchestration.js';
import safety from './safety.js';
import shipping from './shipping.js';
export const chapters = [
  { id: 'foundations', title: '建立工程直觉', subtitle: '从一个请求，看见整个系统', icon: 'layers', lessons: foundations },
  { id: 'runtime', title: '让 Agent 动起来', subtitle: '循环、工具与可靠执行', icon: 'cycle', lessons: runtime },
  { id: 'context', title: '管理信息与记忆', subtitle: '在有限窗口里保留重要内容', icon: 'book', lessons: context },
  { id: 'orchestration', title: '组织协作与交付', subtitle: '把能力连接成可验证的工作流', icon: 'nodes', lessons: orchestration },
  { id: 'safety', title: '守住安全与预算', subtitle: '可控、可停、权限明确', icon: 'shield', lessons: safety },
  { id: 'shipping', title: '测试并交付项目', subtitle: '从能运行，到可维护', icon: 'check', lessons: shipping },
];
export const lessons = chapters.flatMap((chapter, ci) => chapter.lessons.map((lesson, li) => ({ ...lesson, chapter: chapter.id, chapterTitle: chapter.title, chapterIndex: ci, number: ci * 4 + li + 1 })));
export const labs = {
  trace: { title: 'Agent 循环观测台', description: '逐步、回看、自动播放；观察四种运行分支。', icon: 'cycle' },
  schema: { title: '工具参数工作台', description: '编辑 JSON，验证类型与边界，真实执行计算。', icon: 'code' },
  context: { title: '上下文装箱实验', description: '拖动容量，查看保留、舍弃和溢出。', icon: 'layers' },
  retrieval: { title: '迷你检索实验室', description: '本地 TF-IDF 排序，展示匹配词和来源。', icon: 'search' },
  protocol: { title: '协议 X 光机', description: '比较四种请求预设，查看工具 Schema。', icon: 'plug' },
  stream: { title: '流式字节实验', description: '故意切碎中文 SSE，观察事件何时闭合。', icon: 'wave' },
  workflow: { title: '工作流调度沙盘', description: '调整时长，对比串行与并行的关键路径。', icon: 'nodes' },
  memory: { title: '检查点实验', description: '保存、清空临时状态、恢复进度。', icon: 'save' },
  safety: { title: '信任边界实验', description: '观察文本检测、审批与允许动作的区别。', icon: 'shield' },
  cost: { title: 'Token 预算计算器', description: '修改假设单价、缓存量和调用次数。', icon: 'meter' },
  eval: { title: '回归测试台', description: '对比正确实现和错误基线，逐例检查。', icon: 'check' },
};
export const sources = {
  agents: ['Anthropic · Building effective agents', 'https://www.anthropic.com/engineering/building-effective-agents', '工作流与 Agent 的设计模式；课程采用自己的简化实现。'],
  context: ['Anthropic · Effective context engineering', 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents', '上下文选择、压缩与渐进披露。'],
  chat: ['OpenAI · Chat API reference', 'https://developers.openai.com/api/reference/resources/chat', '消息与工具调用的接口字段；具体模型能力以服务文档为准。'],
  responses: ['OpenAI · Responses API reference', 'https://platform.openai.com/docs/api-reference/responses', 'Responses 请求、输出与用量字段。'],
  messages: ['Anthropic · Create a Message', 'https://platform.claude.com/docs/en/api/messages/create', 'Messages 协议及工具内容块。'],
  mcp: ['MCP · Architecture overview', 'https://modelcontextprotocol.io/docs/2026-07-28/learn/architecture', 'Host、Client、Server 与协议能力；注意规范版本。'],
  skills: ['Agent Skills · Overview', 'https://agentskills.io/home', '技能包和按需加载的标准化说明。'],
  async: ['MDN · Introducing asynchronous JavaScript', 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Async_JS/Introducing', '异步操作与 JavaScript 控制流。'],
  schema: ['JSON Schema · Getting started', 'https://json-schema.org/learn/getting-started-step-by-step', '对象结构与字段约束；本站验证器只针对固定计算器。'],
  sse: ['MDN · Using server-sent events', 'https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events', '事件流文本格式与字段。'],
  retrieval: ['Stanford IR Book · Term weighting', 'https://nlp.stanford.edu/IR-book/html/htmledition/term-frequency-and-weighting-1.html', '词项权重与词袋模型；本站中文双字切分是教学选择。'],
  storage: ['MDN · localStorage', 'https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage', '同源持久化、隐私模式与存储异常。'],
  owasp: ['OWASP · LLM Prompt Injection Prevention', 'https://cheatsheetseries.owasp.org/cheatsheets/LLM_Prompt_Injection_Prevention_Cheat_Sheet.html', '提示注入与多层防护；规则演示不构成安全保证。'],
  traces: ['OpenTelemetry · Traces', 'https://opentelemetry.io/docs/concepts/signals/traces/', 'Trace 与 Span 概念；本站未集成其 SDK。'],
  testing: ['Node.js · Test runner', 'https://nodejs.org/api/test.html', '项目测试使用 Node 内置 test runner。'],
  pages: ['GitHub Docs · GitHub Pages', 'https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages', '静态托管能力与边界。'],
};
export const glossary = [
  ['Harness', '围绕模型的运行设施：状态、上下文、工具执行、权限、预算与记录。', 'harness'],
  ['Agent', '围绕目标进行决策、行动、读取反馈的系统。自治程度取决于具体设计。', 'harness'],
  ['Model', '把输入映射到输出的模型；语言模型通常逐词元生成内容。', 'messages'],
  ['Token', '分词器产生的编码单位，不固定等于一个字或一个单词。', 'messages'],
  ['Temperature', '影响采样分布的参数；不是正确率或创造力的精确刻度。', 'messages'],
  ['Context window', '一次模型计算可容纳的上下文范围，具体约束与模型相关。', 'context'],
  ['System prompt', '通过接口规定位置提供的应用层指令，不是普通正文中的标签。', 'messages'],
  ['JSON', '数据交换文本格式；可解析只保证语法，不保证业务正确。', 'javascript'],
  ['Schema', '数据结构合同，描述字段、类型、允许值等。', 'tools'],
  ['Tool calling', '模型提出结构化工具请求，由运行时校验并执行的机制。', 'tools'],
  ['Call ID', '把某次工具请求与其结果配对的标识。', 'tools'],
  ['State machine', '通过事件在明确状态之间转移的运行模型。', 'loop'],
  ['Observation', '来自工具、环境或用户的外部反馈。', 'loop'],
  ['Adapter', '把统一内部合同转换成某种外部协议的模块。', 'protocols'],
  ['Base URL', '服务入口地址；模型标识与端点路径需要另外正确配置。', 'protocols'],
  ['SSE', '以事件形式从服务端向客户端持续传递文本的机制。', 'streaming'],
  ['WebSocket', '双向通信通道；不是所有流式模型接口都使用它。', 'streaming'],
  ['AbortController', '为异步操作提供取消信号的 Web API。', 'streaming'],
  ['Retry', '失败后的再次尝试；需要分类、上限和副作用判断。', 'reliability'],
  ['Idempotency', '重复执行同一操作仍保持预期效果不被重复叠加的性质。', 'reliability'],
  ['RAG', '检索材料后将其提供给生成模型的应用模式。', 'rag'],
  ['Embedding', '文本等对象在向量空间中的表示。', 'rag'],
  ['TF-IDF', '结合词频和逆文档频率的词面权重方法。', 'rag'],
  ['Top-k', '按分数选取前 k 个候选；不是正确答案数量的保证。', 'rag'],
  ['Compaction', '通过摘要等方式压缩历史，减少上下文占用。', 'context'],
  ['Checkpoint', '用于恢复任务的结构化进度快照。', 'memory'],
  ['Skill', '按任务加载的工作说明及相关资源包。', 'skills'],
  ['Workflow', '用预定义步骤与分支组织工作。', 'workflow'],
  ['DAG', '有向无环图，常用来表达不能循环的任务依赖。', 'workflow'],
  ['Delegation', '把子任务交给其他角色，主任务保留后续控制权。', 'multi-agent'],
  ['Handoff', '将后续控制权转交给另一角色的协作方式。', 'multi-agent'],
  ['MCP', '连接 AI 应用与外部工具、资料和模板的协议。', 'mcp'],
  ['Human-in-the-loop', '在关键环节引入明确的人类判断或审批。', 'permissions'],
  ['Prompt injection', '让外部数据中的内容越过信任边界、影响指令或行动的攻击。', 'injection'],
  ['Least privilege', '只授予当前任务必需的操作和资源范围。', 'permissions'],
  ['Sandbox', '限制可访问资源和副作用的隔离环境；能力取决于实际实现。', 'sandbox'],
  ['Artifact', '可检查、保存或交付的成果对象，例如实际生成的 JSON 文件。', 'artifacts'],
  ['Trace / Span', '端到端关联轨迹及其中有起止时间的子操作。', 'traces'],
  ['Eval', '以案例和标准评价系统行为的过程。', 'evals'],
  ['Regression test', '防止已修复问题再次出现的自动化测试。', 'evals'],
  ['CI', '在提交或 PR 后自动运行检查的持续集成流程。', 'deployment'],
];
export const documents = [
  { id: 'doc-1', title: '工具与权限', text: '工具执行前需要检查参数与权限。模型提出工具请求，运行时负责授权。写入任务需要人工确认。' },
  { id: 'doc-2', title: '上下文与记忆', text: '上下文窗口有限。保存历史不等于发送全部历史。检查点保存任务状态，摘要帮助节省容量。' },
  { id: 'doc-3', title: '流式响应与取消', text: 'SSE 事件可能跨越多个网络块。UTF-8 解码需要保留未完成字符。取消请求使用停止信号。' },
  { id: 'doc-4', title: '检索与证据', text: '检索将查询与文档匹配。相关性分数用于排序，不代表事实可靠。回答需要引用证据来源。' },
  { id: 'doc-5', title: '测试与运行记录', text: '回归测试验证错误不会重复出现。运行记录展示阶段、状态和必要错误信息，不保存密钥。' },
];
